version: '3'
services:
  grpc-server:
    container_name: grpc-server
    build:
      context: ./grpc-server
  web:
    container_name: web
    build:
      context: ./web
  restful-api-server:
    container_name: restful-api-server
    build:
      context: ./restful-api-server
  envoy:
    image: envoyproxy/envoy:v1.16-latest
    container_name: envoy
    ports:
    - "80:80"
    - "9901:9901" # admin page
    environment:
    - ENVOY_UID=0
    volumes:
    - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    links:
    - grpc-server
    - restful-api-server
    - web
    depends_on:
    - grpc-server
    - web
    - restful-api-server
