version: '3'
services:
  grpc-server:
    build:
      context: ./grpc-server
  grpc-web:
    build:
      context: ./grpc-web
  envoy:
    image: envoyproxy/envoy:v1.16-latest
    ports:
    - "80:80"
    - "9901:9901" # admin page
    environment:
    - ENVOY_UID=0
    volumes:
    - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    links:
    - grpc-server
    - grpc-web
    depends_on:
    - grpc-server
    - grpc-web
  

